# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: "3.9"

services:
  rust_api:
    container_name: rust_api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - blog_db

  blog_db:
    container_name: blog_db
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: user1
      POSTGRES_USER: user1
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local