# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: "3.9"

services:
  rust_api:
    container_name: rust_api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .envrust
    depends_on:
      blog_db:
        condition: service_healthy
    command: sh -c "diesel migration run && ./blog"

  blog_db:
    container_name: ${POSTGRES_DOCKER_NAME}
    image: "postgres:16-alpine"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local