# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.

version: '3.9'

services:
  app-resto:
    container_name: app-resto
    volumes:
      - src:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .envprod
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app-resto

volumes:
  src: