# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.

version: '3.9'

services:
  app-resto:
    container_name: app-resto
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=prod
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "${NGINX_PORT:-80}:80"