# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.
version: '3.9'

services:
  nodejs-srv:
    build: 
      context: ./server
      dockerfile: Dockerfile
  webapp-clt:
    build:
      context: ./client
      dockerfile: Dockerfile
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - nodejs-srv
      - webapp-clt